# =============================================================================
# build.ps1  -  Build NythosCyberAquarium.scr
# -----------------------------------------------------------------------------
# Steps:
#   1. Embed shaders/*.hlsl into src/Shaders.gen.h as raw string literals so the
#      .scr is self-contained (shaders compiled at runtime via D3DCompile).
#   2. Compile the .rc resources (settings dialog + version info).
#   3. Compile + link all .cpp into build/NythosCyberAquarium.scr (static CRT).
#
# Usage:  pwsh -ExecutionPolicy Bypass -File build.ps1
# =============================================================================
$ErrorActionPreference = "Stop"
$root   = Split-Path -Parent $MyInvocation.MyCommand.Path
$src    = Join-Path $root "src"
$shdir  = Join-Path $root "shaders"
$resdir = Join-Path $root "resources"
$build  = Join-Path $root "build"
New-Item -ItemType Directory -Force -Path $build | Out-Null

# --- 1. Generate embedded shader header --------------------------------------
Write-Host "[1/3] Embedding shaders..." -ForegroundColor Cyan
$genPath = Join-Path $src "Shaders.gen.h"
$sb = [System.Text.StringBuilder]::new()
[void]$sb.AppendLine("// AUTO-GENERATED by build.ps1 - do not edit. Source: shaders/*.hlsl")
[void]$sb.AppendLine("#pragma once")
[void]$sb.AppendLine("namespace nyx { namespace shaders {")
$map = @{ "scene"="scene.hlsl"; "fish"="fish.hlsl"; "particle"="particle.hlsl"; "post"="post.hlsl" }
foreach ($name in $map.Keys) {
    $file = Join-Path $shdir $map[$name]
    $code = Get-Content -Raw -Encoding UTF8 $file
    [void]$sb.AppendLine("inline const char* $name = R""NYXSHADER(")
    [void]$sb.Append($code)
    [void]$sb.AppendLine(")NYXSHADER"";")
}
[void]$sb.AppendLine("}} // namespace nyx::shaders")
Set-Content -Path $genPath -Value $sb.ToString() -Encoding UTF8
Write-Host "      -> $genPath"

# --- locate vcvars (portable across VS version/edition, incl. CI runners) ----
$vswhere = "${env:ProgramFiles(x86)}\Microsoft Visual Studio\Installer\vswhere.exe"
$vcvars = $null
if (Test-Path $vswhere) {
    $vsPath = & $vswhere -latest -products * `
        -requires Microsoft.VisualStudio.Component.VC.Tools.x86.x64 `
        -property installationPath
    if ($vsPath) {
        $candidate = Join-Path $vsPath "VC\Auxiliary\Build\vcvars64.bat"
        if (Test-Path $candidate) { $vcvars = $candidate }
    }
}
if (!$vcvars) {
    # Fallback: check common hardcoded locations (adjust if you install elsewhere)
    foreach ($p in @(
        "C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\Build\vcvars64.bat",
        "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat",
        "C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Auxiliary\Build\vcvars64.bat"
    )) {
        if (Test-Path $p) { $vcvars = $p; break }
    }
}
if (!$vcvars) { throw "vcvars64.bat not found — is the Desktop C++ workload installed?" }

# --- 2 + 3. Compile resources, then sources, inside the VC environment -------
$cpps = (Get-ChildItem -Path $src -Filter *.cpp | ForEach-Object { '"' + $_.FullName + '"' }) -join ' '
$rc   = Join-Path $resdir "NythosCyberAquarium.rc"
$res  = Join-Path $build  "NythosCyberAquarium.res"
$out  = Join-Path $build  "NythosCyberAquarium.scr"

$cmd = @"
call "$vcvars" >nul
echo [2/3] Compiling resources...
rc /nologo /fo "$res" "$rc"
if errorlevel 1 exit /b 1
echo [3/3] Compiling and linking...
cl /nologo /std:c++17 /EHsc /O2 /MT /GS /DUNICODE /D_UNICODE /D_CRT_SECURE_NO_WARNINGS ^
   /I"$src" /I"$resdir" ^
   $cpps "$res" ^
   /Fo"$build\\" /Fe"$out" ^
   /link /SUBSYSTEM:WINDOWS /OPT:REF /OPT:ICF ^
   user32.lib gdi32.lib advapi32.lib
exit /b %errorlevel%
"@

$bat = Join-Path $build "_compile.bat"
Set-Content -Path $bat -Value $cmd -Encoding Ascii
& cmd /c "`"$bat`""
if ($LASTEXITCODE -ne 0) { throw "Build failed (exit $LASTEXITCODE)" }

Write-Host "`nBuild succeeded:" -ForegroundColor Green
Write-Host "  $out"
