// AUTO-GENERATED by build.ps1 - do not edit. Source: shaders/*.hlsl
#pragma once
namespace nyx { namespace shaders {
inline const char* post = R"NYXSHADER(
// =============================================================================
// post.hlsl  -  HDR post-processing chain
// -----------------------------------------------------------------------------
// Pipeline: HDR scene -> bright-pass -> separable Gaussian blur (H then V) ->
// composite (scene + bloom) with ACES filmic tonemap, subtle water distortion,
// chromatic edge and grain. Keeps the look soft and cinematic, not blown out.
//
// Entry points:  VSFullscreen, PSBright, PSBlurH, PSBlurV, PSComposite
// =============================================================================

cbuffer Frame : register(b0)
{
    float2 uResolution;
    float  uTime;
    float  uAspect;
    float  uLighting;
    float  uThreat;
    int    uTheme;
    float  _pad0;
};

Texture2D    gTex   : register(t0);
Texture2D    gBloom : register(t1);
SamplerState gSamp  : register(s0);

struct VSOut { float4 pos : SV_POSITION; float2 uv : TEXCOORD0; };

VSOut VSFullscreen(uint vid : SV_VertexID)
{
    VSOut o;
    float2 p = float2((vid << 1) & 2, vid & 2);
    o.uv  = float2(p.x, p.y);
    o.pos = float4(p * float2(2, -2) + float2(-1, 1), 0, 1);
    return o;
}

float3 ACES(float3 x)
{
    const float a = 2.51, b = 0.03, c = 2.43, d = 0.59, e = 0.14;
    return saturate((x * (a * x + b)) / (x * (c * x + d) + e));
}

// Bright-pass: keep only the energetic highlights for the bloom.
float4 PSBright(VSOut i) : SV_Target
{
    float3 c = gTex.Sample(gSamp, i.uv).rgb;
    float luma = dot(c, float3(0.299, 0.587, 0.114));
    float knee = smoothstep(0.55, 1.1, luma);
    return float4(c * knee, 1.0);
}

static const float kW[5] = { 0.227027, 0.194595, 0.121622, 0.054054, 0.016216 };

float4 PSBlurH(VSOut i) : SV_Target
{
    float2 texel = 1.0 / uResolution;
    float3 r = gTex.Sample(gSamp, i.uv).rgb * kW[0];
    [unroll] for (int k = 1; k < 5; ++k)
    {
        float2 off = float2(texel.x * k * 1.5, 0);
        r += gTex.Sample(gSamp, i.uv + off).rgb * kW[k];
        r += gTex.Sample(gSamp, i.uv - off).rgb * kW[k];
    }
    return float4(r, 1.0);
}

float4 PSBlurV(VSOut i) : SV_Target
{
    float2 texel = 1.0 / uResolution;
    float3 r = gTex.Sample(gSamp, i.uv).rgb * kW[0];
    [unroll] for (int k = 1; k < 5; ++k)
    {
        float2 off = float2(0, texel.y * k * 1.5);
        r += gTex.Sample(gSamp, i.uv + off).rgb * kW[k];
        r += gTex.Sample(gSamp, i.uv - off).rgb * kW[k];
    }
    return float4(r, 1.0);
}

float4 PSComposite(VSOut i) : SV_Target
{
    // Gentle water distortion of the sample coordinate.
    float2 uv = i.uv;
    float2 warp;
    warp.x = sin(uv.y * 40.0 + uTime * 0.8) * 0.0009;
    warp.y = cos(uv.x * 38.0 - uTime * 0.7) * 0.0009;
    uv += warp;

    float3 scene = gTex.Sample(gSamp, uv).rgb;
    float3 bloom = gBloom.Sample(gSamp, uv).rgb;

    float3 col = scene + bloom * 0.9;
    col = ACES(col * (1.05 * uLighting));

    // subtle film grain so flat areas never band
    float g = frac(sin(dot(i.uv * uResolution, float2(12.9898, 78.233)) + uTime) * 43758.5453);
    col += (g - 0.5) * 0.015;

    return float4(col, 1.0);
}
)NYXSHADER";
inline const char* fish = R"NYXSHADER(
// =============================================================================
// fish.hlsl  -  Instanced procedural fish
// -----------------------------------------------------------------------------
// One DrawInstanced call draws the entire school. Per-instance data lives in a
// StructuredBuffer (no input layout needed). The vertex shader places an
// oriented billboard quad in the tank; the pixel shader sculpts the fish with
// an SDF whose centerline undulates along the body (smooth swimming) and bends
// with the turn rate. Far fish fade into the depth fog; cyber creatures glow.
//
// Entry points:  VSFish, PSFish
// =============================================================================

cbuffer Frame : register(b0)
{
    float2 uResolution;
    float  uTime;
    float  uAspect;
    float  uLighting;
    float  uThreat;
    int    uTheme;
    float  _pad0;
};

struct FishInstance
{
    float3 pos;     float  scale;
    float4 tint;
    float  heading; float  phase; float bend; float beat;
    float  species; float  glow;  float pad0; float pad1;
};
StructuredBuffer<FishInstance> gFish : register(t0);

struct VSOut
{
    float4 pos     : SV_POSITION;
    float2 lc      : TEXCOORD0;   // local body coords [-1,1]
    float4 tint    : TEXCOORD1;
    float4 anim    : TEXCOORD2;   // phase, bend, species, glow
    float2 depthA  : TEXCOORD3;   // depth(z), fog amount
};

VSOut VSFish(uint vid : SV_VertexID, uint iid : SV_InstanceID)
{
    FishInstance f = gFish[iid];

    // Triangle-strip quad corners in local body space.
    float2 corners[4] = { float2(-1.35, -1), float2(1.15, -1),
                          float2(-1.35,  1), float2(1.15,  1) };
    float2 lc = corners[vid];

    // Shark is longer & taller; scale the local box a touch.
    bool isShark = (f.species > 5.5);
    float2 box = isShark ? float2(1.5, 0.7) : float2(1.0, 0.62);

    // Depth-driven parallax scale: near fish bigger, far fish smaller.
    float depthScale = lerp(1.15, 0.55, saturate(f.pos.z));
    float2 local = lc * box * f.scale * depthScale;

    // Orient along heading.
    float c = cos(f.heading), s = sin(f.heading);
    float2 world = float2(local.x * c - local.y * s,
                          local.x * s + local.y * c) + f.pos.xy;

    VSOut o;
    o.pos    = float4(world.x / uAspect, world.y, 0.0, 1.0);
    o.lc     = lc;
    o.tint   = f.tint;
    o.anim   = float4(f.phase, f.bend, f.species, f.glow);
    float fog = saturate(f.pos.z) * 0.85;
    o.depthA = float2(f.pos.z, fog);
    return o;
}

// signed helpers
float sdEllipseApprox(float2 p, float2 r) { return length(p / r) - 1.0; }

float4 PSFish(VSOut i) : SV_Target
{
    float2 p = i.lc;                 // [-1.35,1.15] x [-1,1]
    float phase = i.anim.x;
    float bend  = i.anim.y;
    int   species = (int)(i.anim.z + 0.5);
    float glow  = i.anim.w;
    bool  isShark = species == 6;

    // forward = +x (head). tail weight grows toward -x.
    float tailW = smoothstep(0.2, -1.2, p.x);

    // Undulating centerline: tail sweeps, body bends into turns.
    float wave = sin(phase - p.x * 3.0);
    float cy = wave * (isShark ? 0.10 : 0.22) * tailW + bend * 0.22 * (p.x * p.x);
    float y = p.y - cy;

    // Body thickness profile (fat middle, pointed snout, slim caudal peduncle).
    float bx = isShark ? 1.15 : 0.92;
    float prof = saturate(1.0 - pow(saturate(abs(p.x) / bx), isShark ? 1.7 : 1.5));
    float bodyH = (isShark ? 0.34 : 0.40) * pow(prof, 0.55);

    float alpha = 0.0;
    float3 col = i.tint.rgb;

    // --- body ---
    float bodyD = abs(y) - bodyH;
    float body = smoothstep(0.05, -0.02, bodyD) * step(p.x, bx) * step(-1.05, p.x);
    alpha = max(alpha, body);

    // dorsal/ventral shading (back darker, belly lighter)
    float shade = saturate(0.5 - y * 1.3);
    col = lerp(col * 0.55, col * 1.15 + 0.04, shade);

    // --- caudal (tail) fin ---
    float tailX = isShark ? -1.0 : -0.85;
    float tf = smoothstep(0.0, -0.35, p.x - tailX);             // region behind body
    float fanH = (isShark ? 0.85 : 0.6) * smoothstep(tailX - 0.5, tailX, p.x + 0.0);
    float tailFin = tf * smoothstep(0.42, 0.0, abs(y) - fanH * (0.2 + 0.8 * smoothstep(tailX, tailX - 0.45, p.x)));
    // forked look
    tailFin *= (1.0 - 0.6 * smoothstep(0.18, 0.0, abs(y)) * step(p.x, tailX - 0.18));
    float3 finCol = col * 0.8;
    if (tailFin > body) col = finCol;
    alpha = max(alpha, tailFin * 0.95);

    // --- dorsal fin (top) ---
    float df = smoothstep(0.0, 0.1, p.x + 0.3) * smoothstep(0.5, 0.1, p.x);
    float dfTop = bodyH + (isShark ? 0.55 : 0.28) * df;
    float dorsal = smoothstep(0.04, 0.0, abs(y - dfTop * 0.0) - 0.0); // base
    float dorsalFin = step(0.0, y) * smoothstep(0.03, 0.0, (y - dfTop)) * step(dfTop - 0.5, y) * df;
    if (dorsalFin > 0.3 && dorsalFin > body) { col = lerp(col, col * 0.7, 0.5); alpha = max(alpha, dorsalFin * 0.85); }

    // --- clownfish stripes (species 2) ---
    if (species == 2)
    {
        float band = smoothstep(0.05, 0.0, abs(p.x - 0.35)) +
                     smoothstep(0.06, 0.0, abs(p.x + 0.05)) +
                     smoothstep(0.05, 0.0, abs(p.x + 0.55));
        col = lerp(col, float3(0.98, 0.98, 1.0), saturate(band) * body * 0.9);
    }
    // neon tetra (species 3) lateral stripe
    if (species == 3)
        col = lerp(col, float3(0.2, 0.9, 1.0), smoothstep(0.10, 0.0, abs(y + 0.02)) * body * 0.7);

    // --- eye (near head) ---
    float2 ep = float2(p.x - bx * 0.62, y - 0.06);
    float eye = smoothstep(0.06, 0.045, length(ep));
    float pupil = smoothstep(0.03, 0.018, length(ep));
    col = lerp(col, float3(0.95, 0.95, 0.95), eye * body);
    col = lerp(col, float3(0.02, 0.02, 0.03), pupil * body);

    // --- emissive glow for cyber creatures ---
    if (glow > 0.01) col += i.tint.rgb * glow * (0.6 + 0.4 * sin(uTime * 6.0));

    // --- depth fog: fade far fish into the water colour ---
    float fog = i.depthA.y;
    float3 water = lerp(float3(0.06, 0.22, 0.34), float3(0.015, 0.05, 0.11), saturate(i.depthA.x));
    col = lerp(col, water, fog * 0.6);

    // simple top-down lighting sheen
    col += saturate(0.6 - y) * 0.06 * uLighting * body;

    float outA = alpha * i.tint.a * (1.0 - fog * 0.35);
    if (outA < 0.01) discard;
    return float4(col, outA);
}
)NYXSHADER";
inline const char* scene = R"NYXSHADER(
// =============================================================================
// scene.hlsl  -  Procedural underwater reef background
// -----------------------------------------------------------------------------
// A fullscreen pass that paints the whole tank: ocean-depth gradient, drifting
// volumetric god rays, animated caustic shimmer, a noise-sculpted reef floor
// silhouette, depth fog and a soft vignette. Everything animates off uTime with
// incommensurate frequencies so it never visibly loops.
//
// Entry points:  VSFullscreen  (shared fullscreen triangle)
//                PSBackground
// =============================================================================

cbuffer Frame : register(b0)
{
    float2 uResolution;
    float  uTime;
    float  uAspect;
    float  uLighting;
    float  uThreat;     // 0..1, gently warms the water during a "threat" event
    int    uTheme;      // 0 Reef, 1 Abyss, 2 Cyberpunk
    float  _pad0;
};

struct VSOut { float4 pos : SV_POSITION; float2 uv : TEXCOORD0; };

// Fullscreen triangle — no vertex buffer needed.
VSOut VSFullscreen(uint vid : SV_VertexID)
{
    VSOut o;
    float2 p = float2((vid << 1) & 2, vid & 2);   // (0,0)(2,0)(0,2)
    o.uv  = p;                                     // 0..2
    o.pos = float4(p * float2(2, -2) + float2(-1, 1), 0, 1);
    return o;
}

// --- noise toolkit -----------------------------------------------------------
float hash21(float2 p)
{
    p = frac(p * float2(123.34, 345.45));
    p += dot(p, p + 34.345);
    return frac(p.x * p.y);
}
float vnoise(float2 p)
{
    float2 i = floor(p), f = frac(p);
    float2 u = f * f * (3.0 - 2.0 * f);
    float a = hash21(i + float2(0, 0));
    float b = hash21(i + float2(1, 0));
    float c = hash21(i + float2(0, 1));
    float d = hash21(i + float2(1, 1));
    return lerp(lerp(a, b, u.x), lerp(c, d, u.x), u.y);
}
float fbm(float2 p)
{
    float v = 0.0, a = 0.5;
    for (int i = 0; i < 5; ++i) { v += a * vnoise(p); p *= 2.02; a *= 0.5; }
    return v;
}

// Caustic network: domain-warped sine grid, animated.
float caustics(float2 uv, float t)
{
    float2 p = uv * 6.0;
    p += float2(fbm(p * 0.5 + t * 0.05), fbm(p * 0.5 - t * 0.04)) * 1.5;
    float c = 0.0;
    c += sin(p.x * 1.3 + t * 0.9) * sin(p.y * 1.1 - t * 0.7);
    c += sin(p.x * 0.7 - t * 0.6 + 1.7) * sin(p.y * 1.7 + t * 0.5);
    c = c * 0.25 + 0.5;
    return pow(saturate(c), 3.0);
}

float3 ThemeDeep(int theme)
{
    if (theme == 1) return float3(0.01, 0.02, 0.05);   // Abyss
    if (theme == 2) return float3(0.03, 0.02, 0.08);   // Cyberpunk
    return float3(0.015, 0.05, 0.11);                  // Reef
}
float3 ThemeShallow(int theme)
{
    if (theme == 1) return float3(0.04, 0.10, 0.18);
    if (theme == 2) return float3(0.10, 0.06, 0.22);
    return float3(0.06, 0.22, 0.34);
}

float4 PSBackground(VSOut i) : SV_Target
{
    float2 uv = i.uv;                       // 0..1 across the visible screen
    float2 suv = float2(uv.x * uAspect, uv.y);
    float t = uTime;

    // --- depth gradient (top lit, bottom dark) --------------------------
    float depth = saturate(uv.y);
    float3 col = lerp(ThemeShallow(uTheme), ThemeDeep(uTheme), pow(depth, 0.8));

    // --- volumetric god rays from upper area ----------------------------
    float2 lightDir = normalize(float2(0.15, 1.0));
    float rays = 0.0;
    float2 sp = suv;
    [unroll] for (int s = 0; s < 6; ++s)
    {
        sp -= lightDir * 0.06;
        float n = fbm(float2(sp.x * 3.0 + t * 0.06, sp.y * 1.2 - t * 0.10));
        rays += n;
    }
    rays /= 6.0;
    float rayMask = saturate(1.0 - uv.y) * saturate(1.0 - abs(suv.x - uAspect * 0.45) * 0.5);
    col += float3(0.12, 0.24, 0.30) * rays * rayMask * 2.2 * uLighting;

    // --- caustic shimmer (stronger near the surface) --------------------
    float ca = caustics(suv, t);
    col += float3(0.12, 0.22, 0.26) * ca * saturate(1.0 - uv.y * 1.3) * uLighting * 1.3;

    // =====================================================================
    //  LAYERED REEF  (side-on view: the reef rises from the bottom edge,
    //  with depth built from a hazy far ridge, colourful mid coral, swaying
    //  kelp, a sandy bed, and dark foreground coral framing the corners).
    //  uv.y: 0 = surface (top), 1 = tank floor (bottom).
    // =====================================================================
    float fx = suv.x;

    // --- (1) far reef ridge: a distinct hazy silhouette band behind coral -
    float farH    = 0.42 + 0.12 * fbm(float2(fx * 1.1, 11.0)) + 0.05 * sin(fx * 1.7 + 1.3);
    float farLine = 1.0 - farH;
    float farMask = smoothstep(farLine - 0.06, farLine + 0.02, uv.y);
    float3 farCol = float3(0.04, 0.12, 0.18);                            // murky blue ridge
    col = lerp(col, farCol, farMask * 0.85);

    // --- (2) swaying kelp / sea grass rising tall from the reef ----------
    float kelp = 0.0;
    [unroll] for (int kk = 0; kk < 13; ++kk)
    {
        float seed = frac(sin(kk * 91.7) * 4137.13);
        float kx   = (seed * 2.0 - 1.0) * uAspect * 0.98;
        float rootH = 0.28 + 0.26 * frac(sin(kk * 33.3) * 982.4);        // strand height
        float rootY = 1.0;                                              // grows from floor
        float topY  = rootY - rootH;
        float grow  = smoothstep(rootY, topY, uv.y);                    // 0 root .. 1 tip
        float sway  = sin(t * (0.6 + seed) + kk + uv.y * 6.0) * 0.06 * grow;
        float dx    = abs(fx - (kx + sway));
        float strand = smoothstep(0.020, 0.004, dx)
                     * smoothstep(rootY + 0.01, rootY - 0.02, uv.y)
                     * step(topY, uv.y);
        kelp = max(kelp, strand * (0.45 + 0.55 * grow));
    }
    float3 kelpCol = lerp(float3(0.04, 0.20, 0.10), float3(0.10, 0.42, 0.20), 0.5);
    col = lerp(col, kelpCol, kelp * 0.9);

    // --- (3) main coral reef: tall chunky mounds, vivid colour, AO + rim --
    float midH    = 0.26 + 0.14 * fbm(float2(fx * 2.3, 4.0)) + 0.06 * fbm(float2(fx * 6.5, 9.0));
    float midLine = 1.0 - midH;
    float midMask = smoothstep(midLine - 0.025, midLine + 0.010, uv.y);

    float hueN = fbm(float2(fx * 3.1, 2.0));
    float3 coralGreen  = float3(0.16, 0.50, 0.32);
    float3 coralPurple = float3(0.52, 0.22, 0.60);
    float3 coralOrange = float3(0.80, 0.40, 0.16);
    float3 midCol = lerp(coralGreen, coralPurple, smoothstep(0.30, 0.70, hueN));
    midCol = lerp(midCol, coralOrange, smoothstep(0.60, 0.92, fbm(float2(fx * 5.0, 7.0))));
    midCol *= 0.65 + 0.55 * fbm(float2(fx * 24.0, uv.y * 24.0));         // bumpy texture
    // ambient occlusion toward the base so mounds feel rounded; lift overall
    midCol *= lerp(0.55, 1.25, smoothstep(midLine + 0.12, midLine - 0.02, uv.y));
    midCol = midCol * (0.7 + 0.5 * uLighting) + 0.025;                   // brighten + ambient
    col = lerp(col, midCol, midMask);

    // rim light + caustics catching the coral crest
    float crest = smoothstep(midLine + 0.06, midLine - 0.01, uv.y) * midMask;
    col += (float3(0.18, 0.38, 0.34) + float3(0.20, 0.26, 0.28) * ca) * crest * uLighting;

    // --- (4) sandy bed lit by caustics at the very bottom ----------------
    float sandLine = 0.965;
    float sandMask = smoothstep(sandLine - 0.02, sandLine + 0.01, uv.y) * (1.0 - midMask * 0.9);
    float3 sand = lerp(float3(0.16, 0.20, 0.20), float3(0.24, 0.27, 0.25),
                       fbm(float2(fx * 26.0, uv.y * 10.0)));
    sand += caustics(suv * 1.6, t * 1.1) * 0.16;                         // dappled light
    col = lerp(col, sand, sandMask);

    // --- (5) foreground coral framing the lower corners (depth) ----------
    float edge   = smoothstep(uAspect * 0.70, uAspect * 1.00, abs(fx));
    float framH  = 0.50 + 0.34 * fbm(float2(fx * 3.5, 20.0));
    float framLine = 1.0 - framH;
    float framMask = edge * smoothstep(framLine - 0.03, framLine + 0.03, uv.y);
    col = lerp(col, float3(0.010, 0.030, 0.045), framMask * 0.92);       // near-black silhouette

    // --- threat warmth (subtle red push during cyber events) ------------
    col = lerp(col, col * float3(1.25, 0.85, 0.85) + float3(0.04, 0.0, 0.0), uThreat * 0.35);

    // --- vignette -------------------------------------------------------
    float2 q = uv - 0.5;
    float vig = smoothstep(0.95, 0.35, length(q * float2(uAspect, 1.0)));
    col *= lerp(0.65, 1.0, vig);

    return float4(col, 1.0);
}
)NYXSHADER";
inline const char* particle = R"NYXSHADER(
// =============================================================================
// particle.hlsl  -  Instanced bubbles and suspended motes
// -----------------------------------------------------------------------------
// Billboard point sprites from a StructuredBuffer. Bubbles get a refractive rim
// + highlight; motes are soft round specks. Additive-ish blend handled by the
// renderer's blend state.
//
// Entry points:  VSParticle, PSParticle
// =============================================================================

cbuffer Frame : register(b0)
{
    float2 uResolution;
    float  uTime;
    float  uAspect;
    float  uLighting;
    float  uThreat;
    int    uTheme;
    float  _pad0;
};

struct ParticleInstance
{
    float3 pos;  float size;
    float4 color;
    float  kind; float pad0; float pad1; float pad2;
};
StructuredBuffer<ParticleInstance> gParticles : register(t0);

struct VSOut
{
    float4 pos   : SV_POSITION;
    float2 uv    : TEXCOORD0;     // [-1,1] sprite space
    float4 color : TEXCOORD1;
    float  kind  : TEXCOORD2;
};

VSOut VSParticle(uint vid : SV_VertexID, uint iid : SV_InstanceID)
{
    ParticleInstance p = gParticles[iid];
    float2 corners[4] = { float2(-1, -1), float2(1, -1), float2(-1, 1), float2(1, 1) };
    float2 c = corners[vid];

    float depthScale = lerp(1.2, 0.5, saturate(p.pos.z));
    float2 world = p.pos.xy + c * p.size * depthScale;

    VSOut o;
    o.pos   = float4(world.x / uAspect, world.y, 0, 1);
    o.uv    = c;
    o.color = p.color;
    o.kind  = p.kind;
    return o;
}

float4 PSParticle(VSOut i) : SV_Target
{
    float r = length(i.uv);
    if (r > 1.0) discard;

    if (i.kind < 0.5)
    {
        // Bubble: bright thin rim + small specular highlight, hollow centre.
        float rim   = smoothstep(1.0, 0.82, r) * smoothstep(0.6, 0.95, r);
        float hi    = smoothstep(0.35, 0.0, length(i.uv - float2(-0.35, 0.35)));
        float body  = smoothstep(1.0, 0.9, r) * 0.12;
        float a = (rim * 0.9 + hi * 0.8 + body) * i.color.a;
        float3 c = i.color.rgb + hi * 0.5;
        return float4(c, a);
    }
    else
    {
        // Mote: soft round speck.
        float a = smoothstep(1.0, 0.0, r) * i.color.a;
        return float4(i.color.rgb, a);
    }
}
)NYXSHADER";
}} // namespace nyx::shaders

